config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :password_resets, except: %i(index show destroy)
    resources :users do
      collection do
        resources :changes_password, only: %i(edit update)
      end
    end

    resources :morning_speech_schedule, except: %i(edit)
  end
end

app/controllers/changes_password_controller.rb
class ChangesPasswordController < ApplicationController
  before_action :load_user, :correct_user, only: %i(edit update)

  def edit; end

  def update
    if @user.authenticate(params[:user][:password_old]) && @user.update(update_params)
      flash[:success] = t ".success"
      redirect_to @user
    else
      flash[:danger] = t ".failed"
      render :edit
    end
  end

  private

  def update_params
    params.require(:user).permit User::PASSWORD_PARAMS
  end

  def load_user
    @user = User.find_by id: params[:id]

    return if @user
    flash[:danger] = t ".error"
    redirect_to root_path
  end

  def correct_user
    return if current_user? @user
    redirect_to root_url
    flash[:danger]  = t ".not_access"
  end
end

app/views/changes_password/edit.html.erb
<% provide :title, t(".title") %>
<div class="panel panel-primary">
  <div class="panel-heading"><%= t ".title" %></div>
  <div class="panel-body">
    <div class="col-md-8 col-md-offset-2">
      <%= form_for @user, url: changes_password_path(params[:id]), html: {class: "login-form"} do |f| %>
        <%= render "shared/error_messages", object: f.object %>

        <%= hidden_field_tag :email, @user.email %>

        <%= f.label :password_old, t(".password_old") %>
        <%= f.password_field :password_old, class: "form-control", placeholder: t(".pl_password_old") %>

        <%= f.label :password, t(".password") %>
        <%= f.password_field :password, class: "form-control", placeholder: t(".pl_password") %>

        <%= f.label :password_confirmation, t(".password_conf") %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: t(".pl_password_conf") %>

        <div class="col-md-4 col-md-offset-4">
          <%= f.submit t(".submit"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="panel-footer"></div>
</div>