config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"

    resources :password_resets, except: %i(index show destroy)
    resources :users do
      collection do
        resources :changes_password, only: %i(edit update)
      end
    end

    resources :morning_speech_schedule, except: %i(edit)
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer">
    <p class="center"><%= t ".content" %></p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="logo">
    <%= link_to t(".logo"), "#" %>
  </div>
  <div class="dropdown">
    <button class="dropbtn"><i class="fa fa-fw fa-wrench"></i><%= t ".language" %>
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <%= link_to t(".english"), locale:"en" %>
      <%= link_to t(".vietnam"), locale:"vi" %>
    </div>
  </div>
  <% if logged_in? %>
    <div class="dropdown">
      <button class="dropbtn"><i class="fa fa-fw fa-user"></i><%= current_user.name %>
        <i class="fa fa-caret-down"></i>
      </button>
      <div class="dropdown-content">
        <%= link_to t(".profile"), current_user %>
        <%= link_to t(".update_profile"), edit_user_path(current_user) %>
        <%= link_to t(".change_password"), edit_changes_password_path(current_user.id) %>
        <%= link_to t(".logout"), logout_path, method: :delete %>
      </div>
    </div>
    <div class="dropdown">
      <button class="dropbtn"><i class="fa fa-bell"></i><i class="fa fa-caret-down"><%= t ".notification" %></i>
      </button>
      <div class="dropdown-content">
        <%= link_to t(".notification"), "#" %>
      </div>
    </div>
  <% else %>
    <%= link_to login_path do %>
      <i class="fa fa-fw fa-user"></i>
      <%= t ".login" %>
    <% end %>
    <%= link_to about_path do %>
      <i class="fa fa-info-circle"></i>
      <%= t ".about" %>
    <% end %>
    <%= link_to help_path do %>
      <i class="fa fa-question-circle"></i>
      <%= t ".help" %>
    <% end %>
    <%= link_to root_path do %>
      <i class="fa fa-fw fa-home"></i>
      <%= t ".home" %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_sidebar.html.erb
<div class="wrapper">
  <nav class="sidebar">
    <div class="sidebar-header">
      <h3><%= t ".morning_speech" %></h3>
    </div>
    <ul class="list-unstyled components">
      <li><%= link_to t(".dashboard"), morning_speech_schedule_index_path %></li>
      <li>
        <%= link_to t(".calendar"), "#Topic1Submenu", data: {toggle: "collapse"}, aria: {expanded: "false"}, class: "dropdown-toggle" %>
        <ul class="collapse list-unstyled" id="Topic1Submenu">
          <li>
            <%= link_to t(".create_schedule"), new_morning_speech_schedule_path %>
          </li>
          <li>
            <%= link_to t(".sub2_topic1"), "#" %>
          </li>
          <li>
            <%= link_to t(".sub3_topic1"), "#" %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(".topic2"), "#" %>
      </li>
      <li>
        <%= link_to t(".topic2"), "#Topic2Submenu", data: {toggle: "collapse"}, aria: {expanded: "false"}, class: "dropdown-toggle" %>
        <ul class="collapse list-unstyled" id="Topic2Submenu">
          <li>
            <%= link_to t(".sub1_topic2"), "#" %>
          </li>
          <li>
            <%= link_to t(".sub2_topic2"), "#" %>
          </li>
          <li>
            <%= link_to t(".sub3_topic2"), "#" %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to t(".topic3"), "#" %>
      </li>
      <li>
        <%= link_to t(".topic4"), "#" %>
      </li>
    </ul>
    <ul class="list-unstyled foot-nav">
      <li>
        <%= link_to t(".topic5"), "#" %>
      </li>
      <li>
        <%= link_to t(".topic6"), "#" %>
      </li>
    </ul>
  </nav>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button type="button" class="sidebarCollapse btn">
        <i class="fa fa-bars" aria-hidden="true"></i>
      </button>
      <div class="content">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag Settings.awesome_font %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if logged_in? %>
      <%= render "layouts/sidebar" %>
    <% else %>
      <%= render "layouts/flash" %>
      <%= yield %>
    <% end %>
    <%= render "layouts/footer" %>
  </body>
</html>